version: '3'

services:
  web:
    build: .
    command: uvicorn src.app.main:app --host 0.0.0.0 --port 8000
    volumes: 
      - .:/code 
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres123 
      POSTGRES_DB: postgres 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./src/db_data:/docker-entrypoint-initdb.d/
  
volumes:
  postgres_data: